[package]
name = "plaquette"
version = "0.0.0"
authors = ["Aliénore Bouttefeux <alienore.bouttefeux@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/ABouttefeux/plaquette"
categories = ["Science", "Simulation"]
publish = false


[dependencies]
nalgebra = { version = "0.26.2", features = ["serde-serialize"] }
lattice-qcd-rs = {git = "https://github.com/ABouttefeux/lattice-qcd-rs", branch = "develop"}
